# Generated by Django 3.0.8 on 2020-10-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_topup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('topped up', 'topped up'), ('cancelled', 'cancelled')], default='pending', max_length=9),
        ),
    ]
