# Generated by Django 3.0.8 on 2020-11-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('topped up', 'topped up'), ('canceled', 'canceled')], default='pending', max_length=9),
        ),
    ]
