# Generated by Django 3.0.8 on 2020-11-29 21:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201103_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cloud_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='cloud_image'),
        ),
    ]
