# Generated by Django 3.0.8 on 2020-11-29 22:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_company_cloud_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cloud_image',
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
