# Generated by Django 3.0.8 on 2020-09-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='item',
            new_name='product',
        ),
    ]
