# Generated by Django 3.0.8 on 2020-09-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200912_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order_item',
            old_name='item_name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('paid', 'paid'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='received', max_length=12),
        ),
    ]
