# Generated by Django 3.0.8 on 2020-10-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200918_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='option',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
