# Generated by Django 3.0.8 on 2020-10-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201003_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='addon',
            new_name='selection',
        ),
    ]
