# Generated by Django 3.0.8 on 2020-11-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20201028_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=12),
        ),
    ]
